# Generated by Django 5.2.6 on 2025-09-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonenergydata',
            options={},
        ),
    ]
