# Generated by Django 5.2.6 on 2025-09-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_app', '0002_alter_commonenergydata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonEnergyData',
        ),
    ]
