# Generated by Django 5.2.6 on 2025-09-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_app', '0003_delete_commonenergydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlEscalationMaster',
        ),
    ]
