# Generated by Django 5.2.6 on 2025-09-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_app', '0004_delete_alescalationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlEscalationMaster',
            fields=[
                ('site_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_collation='utf8_general_ci', max_length=50)),
                ('site_number', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('imei', models.CharField(db_collation='utf8_general_ci', max_length=20, unique=True)),
                ('l1_number', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=20, null=True)),
                ('l2_number', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=20, null=True)),
                ('l3_number', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=20, null=True)),
                ('l4_number', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=20, null=True)),
                ('l5_number', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=20, null=True)),
                ('btlv_level', models.FloatField(blank=True, null=True)),
                ('temp_level', models.FloatField(blank=True, null=True)),
                ('alarm_mask', models.PositiveIntegerField()),
                ('update_dt', models.DateTimeField()),
                ('client', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('circle', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('zone', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('cluster', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('site_id_ref', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('global_id', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('site_name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=50, null=True)),
                ('ver', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=30, null=True)),
                ('volt_offset', models.FloatField()),
                ('temp_offset', models.FloatField()),
                ('inc_dt', models.DateField()),
                ('create_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'al_escalation_master',
                'managed': False,
            },
        ),
    ]
