# Generated by Django 5.2.6 on 2025-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_app', '0005_alescalationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmsAlarmCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=32)),
                ('site_id', models.CharField(max_length=64)),
                ('site_name', models.CharField(max_length=128)),
                ('cluster_id', models.CharField(max_length=64)),
                ('dist_id', models.CharField(max_length=64)),
                ('state_id', models.CharField(max_length=64)),
                ('DOOR_ALARM', models.BooleanField()),
                ('MAINS_FAIL', models.BooleanField()),
                ('DG_ON', models.BooleanField()),
                ('DG_Failed_to_start', models.BooleanField()),
                ('DG_FUEL_LEVEL_LOW1', models.BooleanField()),
                ('SITE_ON_BATTERY', models.BooleanField()),
                ('HIGH_TEMPERATURE', models.BooleanField()),
                ('FIRE_and_SMOKE', models.BooleanField()),
                ('LOW_BATTERY_VOLTAGE', models.BooleanField()),
                ('EMERGENCY_FAULT', models.BooleanField()),
                ('LLOP_FAULT', models.BooleanField()),
                ('DG_OVERLOAD', models.BooleanField()),
                ('DG_FUEL_LEVEL_LOW2', models.BooleanField()),
                ('ALTERNATOR_FAULT', models.BooleanField()),
                ('DG_Failed_to_stop', models.BooleanField()),
                ('reserve', models.CharField(blank=True, max_length=128, null=True)),
                ('created_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rms_alarm_common_table',
                'managed': False,
            },
        ),
    ]
